### PR TITLE
WIP: glitch!

### PR DESCRIPTION
**Pull request by jsantell**
Reproducible PR for recreating issue in #239 -- should pretty much affect all model viewer instances.

screenshot from 2018-12-06 13-11-53
screenshot from 2018-12-06 13-12-42

### CODE REVIEW

**Comment by jsantell** [comment]
with a lot of `[.WebGL-0x348cba2bf300]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.`, stripped it down just to the setting of the render target, and this error makes a bit more sense. Although not the culprit of #239, may be a similar cause.

**Comment by mrdoob** [comment]
Looks as if the depth buffer had not been cleared from the previous frame.

**Comment by mrdoob** [comment]
I do not think this is the same issue as #239.

**Comment by jsantell** [comment]
Note I encountered this in another environment and it was indeed a depth buffer.

**Pull request closed without merging**
