### PR TITLE
backported soft shadow fix from three

### LINKED ISSUE #942: Regression: white objects suddenly render yellow or blue
### Description

Regression: white objects suddenly render yellow or blue.
Some parts of models that don't use textures have started to render yellow or blue.

IMG_20191220_003317
IMG_20191220_003508
IMG_20191220_003300

The bike parts above and the cubes around the shark are untextured and should render white; they did when I uploaded those models.

#### Live Demo
https://sleet-kookaburra.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [] Windows

### Versions

- model-viewer: latest

### LINKED ISSUE #947: Seeing purple noise when viewing assets in Model-Viewer 8.0 on a Pixel 3
### Description

Noticed that, after updating a test page to use Model-Viewer 8.0, I am now seeing purple noise appear on the surface of that model.

#### Live Demo

Provided via DM

### Browser Affected

- [X ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.8.0
- three.js: rXX

### PR DESCRIPTION
**Pull request by elalish**
Fixes #942 
Fixes #947 

This is a backport of https://github.com/mrdoob/three.js/pull/18328

Some more testing would be great, but this seems to have fixed both issues for me on my Pixel 3.

### CODE REVIEW

**Comment by cdata** [comment]
LGTM 👍 thanks for the quick turn-around on this. I would be interested to hear feedback from upstream, but it doesn't need to be a blocker for this PR.

**Comment by soraryu** [comment]
I can confirm that this fixes the yellow/blue issues on Xiami Mi 9 with my test cases. Thanks!

**Comment by tiagovignatti** [comment]
Things are fine here in model-viewer but the object in Scene Viewer is texture corrupted, showing some purple-ish colours. Is it possible that the Scene Viewer also may need a similar fix? BTW, what's the best channel to report bugs on it? Thank you!

**Comment by elalish** [comment]
@tiagovignatti Is the purple coming through in AR? I'll let them know.

**Comment by cdata** [comment]
@tiagovignatti can you share a screenshot of the Scene Viewer issue?

**Comment by tiagovignatti** [comment]
This is the model in model-viewer displaying **right** colours:

Screenshot_20200108-135009_Chrome

This is the model in Scene Viewer (3D) with **wrong** colours:

Screenshot_20200108-135124_Google

Screenshot_20200108-135139_Google

@elalish the model looks wrong both in AR and 3D.

**Comment by cdata** [comment]
@tiagovignatti thanks for the update! Would you also be able to drop the model in here: https://vr.google.com/scene-viewer-preview

And report back if you see any errors or warnings?

**Comment by elalish** [comment]
@tiagovignatti So, neither of those screenshots is actually AR (no camera image). If your phone does not support AR, then SceneViewer actually uses an older version of model-viewer to display the 3D scene. If that's the case, then we've already fixed this. If you can see these errors on top of a camera image, then it's a SceneViewer bug.

**Comment by cdata** [comment]
@elalish I think their phone supports AR (it is showing the AR button and @tiagovignatti reported that it looks wrong in AR).

**Comment by tiagovignatti** [comment]
Correct, my phone is a Samsung S8. I just didn't send the AR screenshot here before. Anyhow, as I said the model looks wrong both in AR and 3D when using Scene Viewer (when in WebXR, things look good though).

 Here's scene-viewer-preview screenshot, which besides the warnings the texture looks good:

image

**Pull request merged**
