### PR TITLE
update to latest filament

### PR DESCRIPTION
**Pull request by smalls**
Filament's `samples/CMakeLists.txt` changed slightly

### CODE REVIEW

**Comment by cdata** [comment]
Do you think this change is related to #434 ? Is this tweak to the patch sufficient to build a working `gltf_renderer`?

**Comment by smalls** [comment]
No, unfortunately. This just corrects a patch that failed to apply with the current assimp-based `gltf_renderer`.

**Comment by cdata** [comment]
LGTM 👍

**Comment by smalls** [comment]
To clarify - this still uses the old glTF library, but that's still supported (we can build & render with Filament).

**Pull request merged**
