### PR TITLE
Remove ROOM_PADDING_SCALE

### LINKED ISSUE #527: ROOM_PADDING_SCALE is unnecessary
### Description

This is just a simple code cleanup thing, but there is no need to pad the room, as the camera near plane is not set by the room's dimensions. Also, once #526 is merged, there won't even be a room anymore. Removing this will simplify things, but will also slightly change default framing, thus changing the fidelity tests.

### PR DESCRIPTION
**Pull request by elalish**
### Reference Issue
Fixes #527, #537 

As noted in #526, the room padding has not been necessary for awhile, so this removes it for code clarity, especially since there is no longer a room. It has the effect of slightly zooming in all of our fidelity tests and removing the thin boarders around the square ones, as framing is now tight. Thus, all the golden images have been updated.

### CODE REVIEW

**Comment by cdata** [comment]
Our margins were already a bit tight for my liking, if I'm honest. Would it make sense to compensate by adjusting the computed "ideal distance" in order to preserve a bit of the margin?

**Comment by elalish** [comment]
I'm happy to do that if you'd like. One possibility is to change the ideal
distance to the safe distance where any rotation is still fully visible,
though that might be more margin than you want. Also, the margin you see is
highly dependent on how much the model fills its bounding box. Are there
particular models in our fidelity tests that you don't like the framing of?
Really the change is quite subtle.

**Comment by cdata** [comment]
@elalish I would say that the antique camera is an example where the margin makes a big difference in the framing. Check out the bottom of the model, where the front leg of the tripod approaches the edge of the frame:

image

**Comment by elalish** [comment]
Closing as out of date, since some of the cleanup here has landed elsewhere. May revisit later.

**Pull request closed without merging**
