### PR TITLE
Updated demos

### PR DESCRIPTION
**Pull request by Frazer**
Removed defunct demo and added links to most demos in the examples folder.

### CODE REVIEW

**Comment by cdata** [comment]
Hi, thanks for the contribution. This demo is not actually defunct, however, and the others are linked from our documentation.

**Comment by Frazer** [comment]
Have you looked at that link - https://model-viewer.glitch.me .  It changed yesterday, to be a trivial example.

**Comment by cdata** [comment]
Yes, if you fork the Glitch and look at the history, you'll see that demo has always been a trivial example :) it is by design.

**Comment by cdata** [comment]
I'm going to close this one out, but we can re-open if it seems like there is something actionable.

**Pull request closed without merging**
