### PR TITLE
Update colors on the multiple-element demos to be less Google/Microsoft-looking

### PR DESCRIPTION
**Pull request by jsantell**
screenshot from 2018-11-12 16-39-58

screenshot from 2018-11-12 16-40-16

### CODE REVIEW

**Comment by cdata** [comment]
cc @yuinchien WDYT?

**Comment by yuinchien** [comment]
I'm on this, let me play with some colors and send you the update. Give me 20 mins.

**Comment by yuinchien** [comment]
screen shot 2018-11-12 at 6 21 31 pm
screen shot 2018-11-12 at 6 21 40 pm

How about these colors? A mix of material accent & darker tones seem more balanced.

**Comment by yuinchien** [comment]
/* 8 colors set */
    <div style="display:flex;">
      <model-viewer src="assets/Astronaut.glb" background-color="#FF5252"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#455A64"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#EEFF41"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#40C4FF"></model-viewer>
    </div>
    <div style="display:flex;">
      <model-viewer src="assets/Astronaut.glb" background-color="#651FFF"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#1DE9B6"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#FF4081"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#424242"></model-viewer>
    </div>

    /* 4 colors set */
    <div style="display:flex;">
      <model-viewer src="assets/Astronaut.glb" background-color="#FF5252"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#455A64"></model-viewer>
    </div>
    <div style="display:flex;">
      <model-viewer src="assets/Astronaut.glb" background-color="#EEFF41"></model-viewer>
      <model-viewer src="assets/Astronaut.glb" background-color="#40C4FF"></model-viewer>
    </div>

**Pull request merged**
