### PR TITLE
Introduce environment-image and environment-intensity

### LINKED ISSUE #76: UpdatingElement sets a remove attribute as 'null' for string properties
This seems unexpected, should investigate more, but a string property is reflected as `undefined` on initialization (e.g. for attribute 'foo', `this.foo` is undefined). After setting the property, and subsequently removing (`removeAttribute('foo')`), the reflected value is now stringified null, e.g. `this.foo === 'null'`.

This is unexpected reflection for representing the same state: an element that does not have the attribute in question.

### LINKED ISSUE #122: Lighting: allow different images for IBL and background-image
Feature request from Josh Carpenter

### PR DESCRIPTION
**Pull request by cdata**
This change proposes the introduction of two new user-configurable attribute/properties: `environment-image` and `environment-intensity`. Highlights of the change include:

 - Upgrades `@polymer/lit-element@0.6.x` to `lit-element@2.0.x`
    - Various fixes were necessary to make tests pass after breaking changes from upgrade
 - Adds `environment-image` attribute to control the environment map without affecting the background image or color
 - Adds `environment-intensity` attribute to control the intensity of whatever environment map happens to be used

### Examples

`environment-intensity` oscillating `0.0` - `6.0` | Cycle `environment-image` only | Cycle `background-image` only |
| -------------------------------------------- | ------------------------------- | ----------------------------------- |
reflectionintensityosc|reflectionimageosc|reflectionimagebgosc

### Name rationale

~Terms like environment map and IBL are commonly used to refer to the color information used to approximate the light emitted from physical surfaces in 3D scenes. However, these terms are not as meaningful to folks who do not have a graphics background. In the case of a mirror, puddle or other highly reflective surface, a word that very quickly comes to mind to describe the color information is "reflection." As skybox is the "background", so IBL is the "reflection."~

After a lot of good internal team discussion and [some questionable science](https://twitter.com/0xcda7a/status/1101193335190970369), the attribute names have been changed to `environment-image` and `environment-intensity` respectively. One colleague, when faced with the choice between "reflection" and "environment," responded:

> ok so this is what happened
> i said "obviously reflection"
> and then "oh but if the reflection is changing that means the environment around it is changing!"
> 🤯

Fundamentally speaking, reflectivity is a property of individual materials, and environment is a more technically accurate term.

### Additional comments

This change is larger than I initially anticipated. I began to refactor environment map generation, and then quickly ran up against failing tests because I was not accommodating for #76 properly in some cases. So, rather than further spread the #76 disease, I decided to upgrade us to the latest `lit-element` so that we could benefit from the fix introduced a while back. This prompted additional changes that were difficult to tweeze apart from the original proposal due to the need to make tests pass.

Fixes #122 
Fixes #76

### CODE REVIEW

**Comment by johnpallett** [comment]
Are non-reflective materials and surfaces affected by this attribute? "Reflection" suggests the attribute only affects a certain type of material, i.e. things that are partially or entirely reflective (mirrors, car paint, TVs that are turned off). Does this attribute affect matte paint materials?

**Comment by mrdoob** [comment]
The equation is the same for all materials.
If the material is not reflective (`metalness: 0`), then `reflection-image * 0 = 0` ✌️

**Comment by cdata** [comment]
The literal definition of "reflection" is:

> The throwing back by a body or surface of light, heat, or sound without absorbing it.

If an opaque surface is lit at all, does it not follow that it is "reflecting" light (even if that reflection is not recognizable as a mirrored image of the environment)?

**Comment by cdata** [comment]
FYI names have been changed from `reflection-*` to `environment-*`, updated rationale is in the PR description.

**Pull request merged**
